// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"PetStore/pkg/models/shared"
	"net/http"
)

type AddPetResponse struct {
	ContentType string
	// unexpected error
	Error *shared.Error
	// pet response
	Pet         *shared.Pet
	StatusCode  int
	RawResponse *http.Response
}
