// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"PetStore/pkg/models/shared"
	"net/http"
)

type FindPetsRequest struct {
	// maximum number of results to return
	Limit *int `queryParam:"style=form,explode=true,name=limit"`
	// tags to filter by
	Tags []string `queryParam:"style=form,explode=true,name=tags"`
}

type FindPetsResponse struct {
	ContentType string
	// unexpected error
	Error *shared.Error
	// pet response
	Pets        []shared.Pet
	StatusCode  int
	RawResponse *http.Response
}
