// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// NewPet - Pet to add to the store
type NewPet struct {
	Name string  `json:"name"`
	Tag  *string `json:"tag,omitempty"`
}
